### ISSUE TITLE
Issue with AMD RX Vega GPU

### ISSUE THREAD

**Issue by downfall109** [MrCarroll/runescape-launcher#1]
Hey there,

I've been using this snap with success on Manjaro and Ubuntu, but I have an issue on Fedora 31 where it won't launch, referencing some libraries and AMD GPU lists.

Is there anything I can change? I can't manually build this because snapcraft is behaving a little weird as well.

```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Launching RuneScape
Gtk-Message: 20:32:45.537: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:32:45.538: Failed to load module "pk-gtk-module"
/usr/share/libdrm/amdgpu.ids: No such file or directory
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL hw:0
free(): invalid pointer

```

**Comment by MrCarroll** [comment]
Hey,

When a snap is running with secure confinement and the system is actually enforcing it, it forces consistency on the version of Mesa3D that is shipped. This means that all clients should be using the same OpenGL libraries. There's two exceptions to this:

1) NVidia proprietary drivers, which Snap handles properly, and uses the host system
2) AMD proprietary drivers, which Snap doesn't handle at all, but might in the future

If I had to guess, on Manjaro, the sandboxing isn't actually functional, which means if you were using the proprietary AMD drivers, Snap won't prevent it from doing so. This is a bit more confusing since on Ubuntu you should have full confinement, so if I had to make a guess, you aren't using the proprietary AMD drivers on Ubuntu.

Generally, AMD recommends you don't use their proprietary drivers on Linux anymore as they push their own open source drivers now, "amdgpu", straight to the kernel. There are some scenarios which require the proprietary drivers though, I think Blender is one of them.

So in terms of options, I'd say
1) If possible, stick with the opensource AMD driver, it should be superior for gaming.
2) If you need the proprietary driver, try install the snap with:
"sudo snap install rslauncher --classic", which should disable the Sandboxing and might fix this for you on Fedora
3) If the above doesn't work, you can build the snap yourself and change the "confinement" property in the Snapcraft build file to "classic", and then install your local copy,
sudo snap install local.snap --classic --dangerous

If you're having trouble with 3, I'll help you out with the Snapcraft errors if you post them here, it's sometimes a little finicky.

**Comment by downfall109** [comment]
Thanks so much for the super detailed response! I am not using the proprietary AMD drivers, and I appreciate the advice, because my next step would have been installing them. I did initially try using the --classic flag, but it is strictly enforced like you suggested. I also did try to build the snap myself, but I ran into some problems, mainly the following error:

`Fetched 3788 kB in 0s (0 B/s)                                                                                                                                    
Pulling rs3 
'/root/project/rs3' is not a directory
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
`
I added a source-type of 'local' for all the sources in the snapcraft.yaml file, but it just fails in a chain. Not really sure what's missing.

Cheers,
Jordan

**Comment by MrCarroll** [comment]
The repository should be buildable in the state it's currently in, as long as you run snapcraft in the root of the repository, you shouldn't need to make any other modification than swapping the confinement flag. It should literally go:
* git clone https://github.com/mrcarroll/runescape-launcher
* cd runescape-launcher
* change the confinement to classic in the snapcraft.yaml file
* snapcraft (Whilst still in the repository root directory)

If that isn't working if you do it exactly like that, we could,
* Download the snap file, extract it's contents, change the confinement setting there, repack it, and install that, avoiding the snapcraft tool itself
* Or if you'd like, I could just generate you the latest build with the classic confinement set and put it on Google drive for you to download. Unfortunately I can't push a classic snap to the store due to policies they have regarding actually needing that much access.

In the meantime, I'll keep this problem in the back of my mind and if anything stands out as a fix I can do for the general build, I'll work on it. If it's effecting you, it's likely effecting other people too.

**Comment by MrCarroll** [comment]
Unfortunately, having actually tried making this snap classic, it appears there's a lot of stuff that's not so trivial to fix I'd have to look into doing to make the snap work in classic mode.

Despite that, I think I may have fixed the issue, try installing the snap with this command
sudo snap install rslauncher --channel=stable/amdgpu

If that release works for you, it's a trivial fix so I can deploy it to the regular stable branch as soon as it looks good to you

**Comment by downfall109** [comment]
Thanks so much for all your help so far! I think we're a little closer, but the application crashes with the following log errors:

``WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Launching RuneScape
Gtk-Message: 19:20:25.124: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:20:25.124: Failed to load module "pk-gtk-module"
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL hw:0
free(): invalid pointer
``

I think it's something related to sound?

**Comment by MrCarroll** [comment]
Right, we can eliminate graphics as an issue then, although the fix for that graphics library is now in stable anyway.

The other week, I tested swapping the sound backend the game uses to try and reduce the occurences of the choppy sound output. From my own experiences on Ubuntu, it made a great difference, however I've changed it up again in the latest release. It's now back to using Pulseaudio directly, as such, you might find that the latest release in the stable branch works now, if you use `snap info rslauncher`, it should show revision 28. You might have to `sudo snap refresh` to get it. Since I closed the amdgpu branch, you should transition to the stable branch again automatically, if you're on revision 28, I'm hoping it will work for you now.

If the ALSA backend ends up having been the cause of the error, I'll avoid using it in future. The benefits it brought weren't conclusive enough to stick with it being default unless more people start giving feedback.

**Comment by downfall109** [comment]
Thank you so much for the resolution, yes, it's fixed :) Works perfectly for me now.
